repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
      args: ['--unsafe']
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        description: use MyPy for static type checking
        entry: mypy ipsportal
        pass_filenames: false
        language: system
