kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    ipsportal
  namespace: ipsportal
  name: db
  labels:
    app: ipsportal
spec:
  selector:
    matchLabels:
      app: ipsportal
  template:
    metadata:
      labels:
        app: ipsportal
    spec:
      containers:
      - name: db
        image: mongo:4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongo
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password-CHANGE-ME
        securityContext:
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
        volumeMounts:
        - mountPath: /data/db
          name: mongo
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    ipsportal
  namespace: ipsportal
  name: jaeger
  labels:
    app: ipsportal
spec:
  selector:
    matchLabels:
      app: ipsportal
  template:
    metadata:
      labels:
        app: ipsportal
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.34
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: "9411"
        - name: QUERY_BASE_PATH
          value: /jaeger
        securityContext:
          capabilities:
            drop:
            - ALL
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    ipsportal
  namespace: ipsportal
  name: ipsportal
  labels:
    app: ipsportal
spec:
  selector:
    matchLabels:
      app: ipsportal
  template:
    metadata:
      labels:
        app: ipsportal
    spec:
      containers:
      - name: ipsportal
        image: ghcr.io/hpc-simtools/ips-portal/ipsportal:latest
        imagePullPolicy: Always
        env:
        - name: JAEGER_HOST
          value: jaeger
        - name: MONGO_HOST
          value: db
        - name: MONGO_USERNAME
          value: mongo
        - name: MONGO_PASSWORD
          value: password-CHANGE-ME
        securityContext:
          capabilities:
            drop:
            - ALL
---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  labels:
    ipsportal
  namespace: ipsportal
  name: mongodb-dump
  labels:
    app: ipsportal
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-dump
            image: ghcr.io/hpc-simtools/ips-portal/mongodb-backup:latest
            env:
            - name: MONGODB_DUMP_DIR
              value: /backup
            - name: MONGODB_DATABASE
              value: portal
            - name: MONGODB_HOST
              value: db:27017
            - name: MONGODB_USER
              value: mongo
            - name: MONGODB_PASSWORD
              value: password-CHANGE-ME
            - name: MONGODB_DUMP_FILE_BASE
              value: mongodb-dump.archive.gz
            - name: MONGODB_DUMP_RETAIN_DAYS
              value: "7"
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 59432
            volumeMounts:
            - mountPath: /backup
              name: backup
          restartPolicy: Never
          securityContext:
            fsGroup: 59432
          volumes:
          - hostPath:
              path: /global/u1/r/rwp/ipsportal_backup
              type: Directory
            name: backup
  schedule: 12 3 * * *
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ipsportal
  name: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ipsportal
  name: lb
spec:
  rules:
  - host: lb.ipsportal.development.svc.spin.nersc.org
    http:
      paths:
      - backend:
          serviceName: ipsportal-ingress
          servicePort: 8080
        path: /
      - backend:
          serviceName: jaeger-ingress
          servicePort: 16686
        path: /jaeger
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: db
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:db"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: jaeger
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:jaeger"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: ipsportal
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:ipsportal"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: ipsportal-ingress
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:ipsportal"]'
spec:
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: jaeger-ingress
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:jaeger"]'
spec:
  ports:
  - name: default
    port: 16686
    protocol: TCP
    targetPort: 16686
