kind: Secret
apiVersion: v1
data:
  MONGO_USERNAME: bW9uZ28=
  MONGO_PASSWORD: cGFzc3dvcmQtQ0hBTkdFLU1F
  ME_USERNAME: bW9uZ28=
  ME_PASSWORD: cGFzc3dvcmQ=
metadata:
  namespace: ipsportal
  name: mongo-secrets

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ipsportal
  name: db
  labels:
    app: ipsportal-db
spec:
  selector:
    matchLabels:
      app: ipsportal-db
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ipsportal-db
    spec:
      containers:
      - name: db
        image: mongo:4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /secrets/MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /secrets/MONGO_PASSWORD
        securityContext:
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
        volumeMounts:
        - mountPath: /data/db
          name: mongo
        - mountPath: /secrets
          name: secrets
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
      - name: secrets
        secret:
          secretName: mongo-secrets
          defaultMode: 292

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ipsportal
  name: jaeger
  labels:
    app: ipsportal-jaeger
spec:
  selector:
    matchLabels:
      app: ipsportal-jaeger
  template:
    metadata:
      labels:
        app: ipsportal-jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.35
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: "9411"
        - name: QUERY_BASE_PATH
          value: /jaeger
        securityContext:
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /jaeger
            port: 16686
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /jaeger
            port: 16686
            scheme: HTTP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ipsportal
  name: ipsportal
  labels:
    app: ipsportal-ipsportal
spec:
  selector:
    matchLabels:
      app: ipsportal-ipsportal
  template:
    metadata:
      labels:
        app: ipsportal-ipsportal
    spec:
      containers:
      - name: ipsportal
        image: ghcr.io/hpc-simtools/ips-portal/ipsportal:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mongo-secrets
        env:
        - name: JAEGER_HOST
          value: jaeger
        - name: MONGO_HOST
          value: db
        - name: TZ
          value: America/Los_Angeles
        securityContext:
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ipsportal
  name: me
  labels:
    app: ipsportal-me
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ipsportal-me
  template:
    metadata:
      labels:
        app: ipsportal-me
    spec:
      containers:
      - name: me
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: db
        - name: ME_CONFIG_SITE_BASEURL
          value: /me
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME_FILE
          value: /secrets/MONGO_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD_FILE
          value: /secrets/MONGO_PASSWORD
        - name: ME_CONFIG_BASICAUTH_USERNAME_FILE
          value: /secrets/ME_USERNAME
        - name: ME_CONFIG_BASICAUTH_PASSWORD_FILE
          value: /secrets/ME_PASSWORD
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /secrets
          name: secrets
      volumes:
      - name: secrets
        secret:
          secretName: mongo-secrets

---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  namespace: ipsportal
  name: mongodb-dump
  labels:
    app: ipsportal-mongodb-dump
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-dump
            image: ghcr.io/hpc-simtools/ips-portal/mongodb-backup:latest
            envFrom:
            - secretRef:
                name: mongo-secrets
            env:
            - name: MONGODB_DUMP_DIR
              value: /backup
            - name: MONGODB_DATABASE
              value: portal
            - name: MONGODB_HOST
              value: db:27017
            - name: MONGODB_DUMP_FILE_BASE
              value: mongodb-dump.archive.gz
            - name: MONGODB_DUMP_RETAIN_DAYS
              value: "7"
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 59432
            volumeMounts:
            - mountPath: /backup
              name: backup
          restartPolicy: Never
          securityContext:
            fsGroup: 59432
          volumes:
          - hostPath:
              path: /global/u1/r/rwp/ipsportal_backup
              type: Directory
            name: backup
  schedule: 12 3 * * *

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ipsportal
  name: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ipsportal
  name: lb
spec:
  rules:
  - host: lb.ipsportal.development.svc.spin.nersc.org
    http:
      paths:
      - backend:
          serviceName: ipsportal-ingress
          servicePort: 8080
        path: /
      - backend:
          serviceName: jaeger-ingress
          servicePort: 16686
        path: /jaeger
      - backend:
          serviceName: me-ingress
          servicePort: 8081
        path: /me

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: db
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:db"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: jaeger
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:jaeger"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: me
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:me"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: ipsportal
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:ipsportal"]'
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: ipsportal-ingress
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:ipsportal"]'
spec:
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: jaeger-ingress
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:jaeger"]'
spec:
  ports:
  - name: default
    port: 16686
    protocol: TCP
    targetPort: 16686

---
apiVersion: v1
kind: Service
metadata:
  namespace: ipsportal
  name: me-ingress
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:ipsportal:me"]'
spec:
  ports:
  - name: default
    port: 8081
    protocol: TCP
    targetPort: 8081
