apiVersion: v1
data:
  MONGO_USERNAME: bW9uZ28=
  MONGO_PASSWORD: cGFzc3dvcmQtQ0hBTkdFLU1F
  ME_USERNAME: bW9uZ28=
  ME_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  namespace: ipsportal
  name: mongo-secrets
