name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: environment.yml
    - name: Install testing requirements
      run: mamba env update --file environment_dev.yml
    - name: Lint with flake8
      run: flake8
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 4
    - name: Run tests
      run: python -m pytest --cov --cov-report=xml --cov-report=term tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
