name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install testing requirements
      run: python -m pip install flake8==4.0.1 pytest-cov
    - name: Lint with flake8
      run: flake8
    - name: Start MongoDB and Jaeger
      run: |
        docker run --rm -p 27017:27017 --name mongo -d mongo:4
        docker run --rm -p 9411:9411 -p 16686:16686 --env QUERY_BASE_PATH=/jaeger --env COLLECTOR_ZIPKIN_HOST_PORT=9411 --name jaeger -d jaegertracing/all-in-one:1.31
    - name: Install ipsportal
      run: python -m pip install -e .
    - name: Run tests
      run: python -m pytest --cov --cov-report=xml --cov-report=term tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Stop MongoDB and Jaeger
      run: |
        docker stop mongo
        docker stop jaeger
    - name: Log into registry ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push IPS portal
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/hpc-simtools/ips-portal/ipsportal:latest
        push: true
