name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: environment.yml
    - name: Install testing requirements
      run: mamba env update --file environment_dev.yml
    - name: Lint with flake8
      run: flake8
    - name: Start MongoDB and Jaeger
      run: |
        docker run --rm -p 27017:27017 --name mongo -d mongo:5
        docker run --rm -p 9411:9411 -p 16686:16686 --env QUERY_BASE_PATH=/jaeger --env COLLECTOR_ZIPKIN_HOST_PORT=9411 --name jaeger -d jaegertracing/all-in-one:1.31
    - name: Run tests
      run: python -m pytest --cov --cov-report=xml --cov-report=term tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Stop MongoDB and Jaeger
      run: |
        docker stop mongo
        docker stop jaeger
